Feature/summary component
smarticle-dsd/smarticle pull request #22
Opened 2022-11-27 21:29 UTC by sairaghav

2022-11-27 22:28 UTC, nMedic246 approved these changes
Looks great!

2022-11-27 23:16 UTC, vlahovivan requested changes
Looks good, the only thing I would change is, instead of adding paddings to each of the elements, add a 16px padding to the summary component, and then for each of the elements inside of it, just use margin-bottom (8 or 16px)

2022-11-28 15:30 UTC, nMedic246 approved these changes
I think it works pretty well now!

2022-11-28 19:36 UTC, vlahovivan approved these changes

2022-11-28 19:36 UTC, merged