Referencecomp
smarticle-dsd/smarticle pull request #35
Opened 2022-12-05 11:45 UTC by sanjayssj5

Reference component improved. Implements canvas changes from tooltip  and resizes with sidebar. Opens and toggles sidebar and reference tool onclick reference.

2022-12-05 11:51 UTC, sairaghav requested changes
Please do not push amplify folder if you did not make any changes to it.

2022-12-05 13:15 UTC, sanjayssj5 commented
> Please do not push amplify folder if you did not make any changes to it.

Updated amplify. Using latest version.

2022-12-05 13:20 UTC, sairaghav approved these changes

2022-12-05 14:01 UTC, vlahovivan requested changes
The reference view looks good, but the things I commented should be changed to make the code more readable for others. Other than that, have you maybe tried making the reference canvas a bit taller so more info can be seen? maybe we can also take a look at some panning and zooming solutions for canvas.

Also, I'm not sure what happened with the amplify files, we'll definitely have to take a look at that, maybe add them to ESLint and Prettier ignore files, I'll ping @nMedic246 just in case it's a Husky problem, and @sairaghav just so he's aware of this issue.

2022-12-05 14:01 UTC, vlahovivan commented on src/components/Reference/Reference.scss
> +  .reffwrap {
Please give more descriptive class names, for example `reference-view-wrapper`

2022-12-05 14:01 UTC, vlahovivan commented on src/components/Reference/Reference.scss
> +    .reff {
descriptive class names: same here

2022-12-05 14:01 UTC, vlahovivan commented on src/components/Reference/Reference.scss
> +  .canv {
descriptive class names: same here

2022-12-05 14:01 UTC, vlahovivan commented on public/web/customToolbar.js
> +const togglereftool = () => {
please use lowerCamelCase for function names, you can take a look at https://google.github.io/styleguide/tsguide.html#identifiers

2022-12-05 14:01 UTC, vlahovivan commented on public/web/customToolbar.js
> +  let vall = document.getElementById("referenceDetailsView");
again, more descriptive variable names would make it much easier to do code review

2022-12-05 14:01 UTC, vlahovivan commented on src/components/Reference/Reference.scss
> +      top: 96px;
take a look at `display: flex`, and make the inner div vertically and horizontally aligned instead of giving it a fixed distance from the top

2022-12-05 18:36 UTC, sanjayssj5 commented on src/components/Reference/Reference.scss
> +  .reffwrap {
I have made the requested changes except for panning and zooming. Can they be made as separate backlog in this or next sprint? For Height also it is now increased statically.

2022-12-07 10:15 UTC, vlahovivan commented
Looks good, however I've noticed a few more things:
- in the reference view wrapper, add a `border-radius: 4px;` so it matches the design on Figma
- also in the reference view wrapper, add a `margin-bottom: 16px;` to the image, and `vertical-align: top;` (that removes the extra margin that svg images sometimes have)

Also could we remove the changes made to the files that are not relevant to this PR (specifically Amplify files).

2022-12-07 13:37 UTC, sanjayssj5 commented
Applied changes and restored amplify.

2022-12-07 17:27 UTC, nMedic246 requested changes
It works good!
I added some comments about the scale so the canvas looks a bit cleaner when the sidebar is resized.
Also, I added some changes to[ feature/reference-rework](https://github.com/smarticle-dsd/smarticle/tree/feature/reference-rework) take a look and if it seems alright merge it with this branch, so we have all the reference changes ready for develop.

2022-12-07 17:27 UTC, nMedic246 commented on public/build/pdf.js
> +                      const scalefact = 1;
Please change the scalefact to 1.6, canvas resolution is much better when the sidebar is resized.

2022-12-07 17:27 UTC, nMedic246 commented on public/build/pdf.js
> +                        canv.width = rr.width - 2 * (d - 10);
Change canv.width to:
`canv.width = scalefact*rr.width - 2 * d - 30;
`

2022-12-07 17:27 UTC, nMedic246 commented on public/build/pdf.js
> +                        canv.width = rr.width - d;
Change canv.width to:
`canv.width = scalefact*rr.width - d;`

2022-12-07 17:27 UTC, nMedic246 commented on public/build/pdf.js
> +                        offsetX: (-d + 10) * scalefact,
Change offsetX to:
`offsetX: (-d + 30) * scalefact`

2022-12-07 21:47 UTC, sanjayssj5 commented
done with changes. Pls kindly verify @vlahovivan @nMedic246

2022-12-08 09:29 UTC, nMedic246 approved these changes

2022-12-08 09:31 UTC, vlahovivan approved these changes
Great job!

2022-12-08 09:38 UTC, merged