Sa150/text input
smarticle-dsd/smarticle pull request #65
Opened 2022-12-25 19:13 UTC by sanjayssj5

# Description

Adding a common Input Text component for reuse

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# Reference JIRA tickets : 

- SA-#150

# Checklist:

Put an "x" in the brackets to check the checkbox.

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in particularly hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] I have made corresponding changes to JIRA tickets
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have merged develop into my branch and resolved possible conflicts

2022-12-25 19:18 UTC, sanjayssj5 commented
As of now text input was found in upload modal in home page and sidebar error components. For the CSS part both of them are not similar so used them as it is as  of now.

2022-12-25 22:43 UTC, vlahovivan commented on src/index.tsx
> +////// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
where did this come from?

2022-12-25 22:46 UTC, vlahovivan requested changes
It works well, the only thing I've immediately noticed is that all of the InputText components have the same ID. That causes the suggestions (search history) to be the same for all instances of input. I would suggest adding a custom domID to the input in the upload modal component (something like `sa-upload-modal-input-text`) and doing the same thing for sidebar error (something like `sa-sidebar-error-input-text`).

2022-12-25 23:29 UTC, sanjayssj5 commented
Made the changes. The id must be unique now.

2022-12-25 23:30 UTC, sanjayssj5 commented on src/index.tsx
> +////// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
not sure about this XD

2022-12-26 11:15 UTC, vlahovivan commented on src/components/InputText/InputText.tsx
> +  domID = className?.concat("-input-text"),
I don't think this is an ideal solution, for example if one element has a className "a b c" and the other one has className "c b a" - they will get different IDs even if you expect them to be the same.
I think you should leave this domID as it was, and change it only in InputText instances in UploadModal and SidebarError components

2022-12-26 11:43 UTC, vlahovivan approved these changes

2022-12-26 11:45 UTC, merged