HomePage&UploadModal v1
smarticle-dsd/smarticle pull request #8
Opened 2022-11-10 11:53 UTC by noemi-i

2022-11-10 12:56 UTC, nMedic246 commented
Looks great! I'd suggest to move the icons folder to the public root folder.

2022-11-10 13:03 UTC, nMedic246 commented on src/components/UploadModal/UploadModal.tsx
> +  const linlkUpload = (e: React.KeyboardEvent) => {
is 'linlkUpload' a typo, or is it so on purpose?

2022-11-10 13:05 UTC, noemi-i commented on src/components/UploadModal/UploadModal.tsx
> +  const linlkUpload = (e: React.KeyboardEvent) => {
Yep, it's a typo, I didn't notice that, I'll correct it

2022-11-10 13:18 UTC, noemi-i commented
> Looks great! I'd suggest to move the icons folder to the public root folder.

I've imported icon svgs as ReactComponent, I'm not sure if it's possible from public folder, I'll do some search about it

2022-11-10 13:26 UTC, nMedic246 commented
> I've imported icon svgs as ReactComponent, I'm not sure if it's possible from public folder, I'll do some search about it

Ah yeah, sorry i missed that. Maybe it's ok to leave it like this then, idk,  maybe Ivan has some more knowledge of that.

2022-11-10 19:12 UTC, vlahovivan requested changes
Looks good, there is only a few minor things I've noticed:
- the "or" part is missing in the modal
- left padding in the input box could be increased a bit
  - just add `padding-left: 8px` to `.modal-link-section`
- you can also change the color of input text in `.modal-link-section`, as well as the placeholder
```css
color: var(--sa-neutral-color-5);

&::placeholder {
  color: var(--sa-neutral-color-3);
}
```

After fixing that, and the things that Nika noticed, I think we can merge this and then add the Button component instead of custom buttons once we merge my PR as well.
The other option is to first merge my PR, then add the buttons here, and merge this PR.

2022-11-11 11:22 UTC, nMedic246 approved these changes
I think it's all good now.

2022-11-12 09:29 UTC, vlahovivan approved these changes

2022-11-12 09:30 UTC, merged